services:
  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - phpmyadmin_data:/var/www/html/:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:5.2.1-fpm-alpine
    volumes:
      - phpmyadmin_data:/var/www/html/
    restart: always
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:10.10
    container_name: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_DATABASE=backend
    volumes:
      - ./mariadb-data:/var/lib/mysql
    restart: always
volumes:
  phpmyadmin_data:
